//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Diseno.Modelo
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Cliente : Persona
	{
		public virtual string numeroTarjeta
		{
			get;
			set;
		}

		public virtual IEnumerable<Reserva> Reservas
		{
			get;
			set;
		}

		public virtual void Create(Cliente cliente)
		{
			throw new System.NotImplementedException();
		}

		public virtual void SelectCliente(Cliente cliente)
		{
			throw new System.NotImplementedException();
		}

		public virtual void get(Cliente cliente)
		{
			throw new System.NotImplementedException();
		}

	}
}

