//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Diseno.Modelo
{
	using Diseno.Controlador;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Descuento
	{
		public virtual string nombre
		{
			get;
			set;
		}

		public virtual int porcentaje
		{
			get;
			set;
		}

		public virtual DateTime fechaInicio
		{
			get;
			set;
		}

		public virtual DateTime fechaFin
		{
			get;
			set;
		}

		public virtual int idDescuento
		{
			get;
			set;
		}

		public virtual string descripcion
		{
			get;
			set;
		}

		public virtual IEnumerable<Reserva> Reservas
		{
			get;
			set;
		}

		public virtual void searchDescuentos(DateTime fechaInicio, DateTime fechaFin)
		{
			throw new System.NotImplementedException();
		}

	}
}

