//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Diseno.Modelo
{
	using Diseno.Controlador;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Factura
	{
		public virtual DateTime fechaEmision
		{
			get;
			set;
		}

		public virtual DateTime fechaPago
		{
			get;
			set;
		}

		public virtual bool abono
		{
			get;
			set;
		}

		public virtual int idFactura
		{
			get;
			set;
		}

		public virtual IEnumerable<LineaFactura> LineasFactura
		{
			get;
			set;
		}

		public virtual Reserva Reserva
		{
			get;
			set;
		}

	}
}

