//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Diseno.Modelo
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Habitacion
	{
		public virtual int numero
		{
			get;
			set;
		}

		public virtual int aforo
		{
			get;
			set;
		}

		public virtual string localizacion
		{
			get;
			set;
		}

		public virtual string descripcion
		{
			get;
			set;
		}

		public virtual float precio
		{
			get;
			set;
		}

		public virtual bool ocupada
		{
			get;
			set;
		}

		public virtual IEnumerable<ReservaHabitacion> ReservaHabitacion
		{
			get;
			set;
		}

		public virtual IEnumerable<ReservaServicio> ReservaServicio
		{
			get;
			set;
		}

		public virtual bool getOcupada()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Search(Habitacionr habitacion)
		{
			throw new System.NotImplementedException();
		}

		public virtual void getHabitaciones()
		{
			throw new System.NotImplementedException();
		}

	}
}

