//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Diseno.Modelo
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class LineaPedido
	{
		public virtual int cantidad
		{
			get;
			set;
		}

		public virtual float precio
		{
			get;
			set;
		}

		public virtual int idLineaPedido
		{
			get;
			set;
		}

		public virtual Producto Producto
		{
			get;
			set;
		}

		public virtual Pedido Pedido
		{
			get;
			set;
		}

		public virtual void ConfirmSummary(Producto producto, Proveedor proveedor, int cantidad)
		{
			throw new System.NotImplementedException();
		}

		public virtual void <<create>>(LineaPedido lineapedido)
		{
			throw new System.NotImplementedException();
		}

	}
}

