//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Diseno.Modelo
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Menu : Servicio
	{
		public virtual DateTime horaInicio
		{
			get;
			set;
		}

		public virtual DateTime horaFin
		{
			get;
			set;
		}

		public virtual IEnumerable<PlatoMenu> PlatoMenu
		{
			get;
			set;
		}

		public virtual DateTime getHoraInicio()
		{
			throw new System.NotImplementedException();
		}

		public virtual DateTime getHoraFin()
		{
			throw new System.NotImplementedException();
		}

	}
}

