//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Diseno.Modelo
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class Persona
	{
		public virtual string nif
		{
			get;
			set;
		}

		public virtual string nombre
		{
			get;
			set;
		}

		public virtual int telefono
		{
			get;
			set;
		}

		public virtual string correoElectronico
		{
			get;
			set;
		}

		public virtual string direccion
		{
			get;
			set;
		}

		public virtual string localidad
		{
			get;
			set;
		}

		public virtual string provincia
		{
			get;
			set;
		}

		public virtual string codigoPostal
		{
			get;
			set;
		}

		public virtual string pais
		{
			get;
			set;
		}

		public virtual string apellidos
		{
			get;
			set;
		}

		public virtual int idPersona
		{
			get;
			set;
		}

		public virtual Proveedor Proveedor
		{
			get;
			set;
		}

	}
}

