//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Diseno.Modelo
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Plato
	{
		public virtual string nombre
		{
			get;
			set;
		}

		public virtual int idPlato
		{
			get;
			set;
		}

		public virtual IEnumerable<PlatoMenu> PlatoMenu
		{
			get;
			set;
		}

	}
}

