//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Diseno.Modelo
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ProductoProveedor
	{
		public virtual float precio
		{
			get;
			set;
		}

		public virtual int idProductoProveedor
		{
			get;
			set;
		}

		public virtual Producto Producto
		{
			get;
			set;
		}

		public virtual Proveedor Proveedor
		{
			get;
			set;
		}

	}
}

