//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Diseno.Modelo
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Producto
	{
		public virtual int cantidad
		{
			get;
			set;
		}

		public virtual int limiteMinimo
		{
			get;
			set;
		}

		public virtual string localizador
		{
			get;
			set;
		}

		public virtual string categoria
		{
			get;
			set;
		}

		public virtual string descripcion
		{
			get;
			set;
		}

		public virtual string nombre
		{
			get;
			set;
		}

		public virtual float precio
		{
			get;
			set;
		}

		public virtual int idProducto
		{
			get;
			set;
		}

		public virtual IEnumerable<LineaPedido> LineasPedido
		{
			get;
			set;
		}

		public virtual IEnumerable<ProductoProveedor> ProductoProveedor
		{
			get;
			set;
		}

		public virtual void ShowProductos()
		{
			throw new System.NotImplementedException();
		}

		public virtual List<Producto> getProductos()
		{
			throw new System.NotImplementedException();
		}

	}
}

