//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Diseno.Modelo
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Proveedor
	{
		public virtual string numeroCuenta
		{
			get;
			set;
		}

		public virtual string nombre
		{
			get;
			set;
		}

		public virtual string cif
		{
			get;
			set;
		}

		public virtual string direccion
		{
			get;
			set;
		}

		public virtual string correoElectronico
		{
			get;
			set;
		}

		public virtual string localidad
		{
			get;
			set;
		}

		public virtual string provincia
		{
			get;
			set;
		}

		public virtual string pais
		{
			get;
			set;
		}

		public virtual int idProveedor
		{
			get;
			set;
		}

		public virtual IEnumerable<Pedido> Pedidos
		{
			get;
			set;
		}

		public virtual Persona Persona
		{
			get;
			set;
		}

		public virtual IEnumerable<ProductoProveedor> ProductoProveedor
		{
			get;
			set;
		}

		public virtual void ShowProveedores()
		{
			throw new System.NotImplementedException();
		}

		public virtual List<Proveedor> getProveedores()
		{
			throw new System.NotImplementedException();
		}

	}
}

