//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Diseno.Modelo
{
	using Diseno.Controlador;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ReservaServicio
	{
		public virtual DateTime fechaInicio
		{
			get;
			set;
		}

		public virtual DateTime fechaFin
		{
			get;
			set;
		}

		public virtual int idReservaServicio
		{
			get;
			set;
		}

		public virtual Servicio Servicio
		{
			get;
			set;
		}

		public virtual LineaFactura LineaFactura
		{
			get;
			set;
		}

		public virtual Habitacion Habitacion
		{
			get;
			set;
		}

	}
}

