//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Diseno.Modelo
{
	using Diseno.Controlador;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Reserva
	{
		public virtual DateTime fechaInicio
		{
			get;
			set;
		}

		public virtual DateTime fechaFin
		{
			get;
			set;
		}

		public virtual DateTime fechaRealizacion
		{
			get;
			set;
		}

		public virtual string comentarios
		{
			get;
			set;
		}

		public virtual int regimenComida
		{
			get;
			set;
		}

		public virtual int estado
		{
			get;
			set;
		}

		public virtual int idReserva
		{
			get;
			set;
		}

		public virtual Descuento Descuento
		{
			get;
			set;
		}

		public virtual Factura Factura
		{
			get;
			set;
		}

		public virtual Cliente Cliente
		{
			get;
			set;
		}

		public virtual IEnumerable<ReservaHabitacion> ReservaHabitacion
		{
			get;
			set;
		}

		public virtual int getRegimenComida()
		{
			throw new System.NotImplementedException();
		}

		public virtual int getIdReserva()
		{
			throw new System.NotImplementedException();
		}

		public virtual void setReserva(Reserva reserva)
		{
			throw new System.NotImplementedException();
		}

	}
}

