//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Diseno.Modelo
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Servicio
	{
		public virtual string descripcion
		{
			get;
			set;
		}

		public virtual string nombre
		{
			get;
			set;
		}

		public virtual float precio
		{
			get;
			set;
		}

		public virtual int idServicio
		{
			get;
			set;
		}

		public virtual IEnumerable<ReservaServicio> ReservasServicio
		{
			get;
			set;
		}

		public virtual float getPrecio()
		{
			throw new System.NotImplementedException();
		}

		public virtual int getIdServicio()
		{
			throw new System.NotImplementedException();
		}

	}
}

