//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo se genero mediante una herramienta.
//     Los cambios del archivo se perderan si se regenera el codigo.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;

namespace TeamCatHotel.Models
{
    public class Cliente : Persona
	{
        [Required]
        [DataType(DataType.CreditCard)]
        public virtual string numeroTarjeta
		{
			get;
			set;
		}

		public virtual ICollection<Reserva> Reservas
		{
			get;
			set;
		}

	}
}

