//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo se genero mediante una herramienta.
//     Los cambios del archivo se perderan si se regenera el codigo.
// </auto-generated>
//------------------------------------------------------------------------------

//using Diseno.Controlador;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;

namespace TeamCatHotel.Models
{
    public class Descuento
	{
        [Required]
        [StringLength(100, MinimumLength = 5)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        public virtual string nombre
		{
			get;
			set;
		}

        [Required]
        [Range(0, 100)]
        public virtual int porcentaje
		{
			get;
			set;
		}

        [Required]
        [DataType(DataType.Date)]
        public virtual DateTime fechaInicio
		{
			get;
			set;
		}

        [Required]
        [DataType(DataType.Date)]
        public virtual DateTime fechaFin
		{
			get;
			set;
		}

        [Key]
        public virtual int idDescuento
		{
			get;
			set;
		}

        [Required]
        [StringLength(200, MinimumLength = 5)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        public virtual string descripcion
		{
			get;
			set;
		}

		public virtual ICollection<Reserva> Reservas
		{
			get;
			set;
		}

	}
}

