//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo se genero mediante una herramienta.
//     Los cambios del archivo se perderan si se regenera el codigo.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;

namespace TeamCatHotel.Models
{
    public class Habitacion
	{
        [Key]
		public virtual int numero
		{
			get;
			set;
		}

        [Required]
		public virtual int aforo
		{
			get;
			set;
		}

        [Required]
        [StringLength(100, MinimumLength = 3)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        public virtual string localizacion
		{
			get;
			set;
		}

        [Required]
        [StringLength(200, MinimumLength = 5)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        public virtual string descripcion
		{
			get;
			set;
		}

        [Required]
        [DataType(DataType.Currency)]
        public virtual float precio
		{
			get;
			set;
		}

        [Required]
        public virtual bool ocupada
		{
			get;
			set;
		}

		public virtual ICollection<ReservaHabitacion> ReservaHabitacion
		{
			get;
			set;
		}

		public virtual ICollection<ReservaServicio> ReservaServicio
		{
			get;
			set;
		}

	}
}

