//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo se genero mediante una herramienta.
//     Los cambios del archivo se perderan si se regenera el codigo.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;

namespace TeamCatHotel.Models
{ 

    public class Menu : Servicio
    {
        [Required]
        [DataType(DataType.Time)]
        public virtual DateTime horaInicio
        {
            get;
            set;
        }

        [Required]
        [DataType(DataType.Time)]
        public virtual DateTime horaFin
        {
            get;
            set;
        }


        public virtual ICollection<PlatoMenu> PlatoMenu
        {
			get;
			set;
		}
	}
}

