//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo se genero mediante una herramienta.
//     Los cambios del archivo se perderan si se regenera el codigo.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;

namespace TeamCatHotel.Models
{
    public abstract class Persona
	{
        [Required]
        [RegularExpression(@"^(\d{8}[A-Z])$")]
        public virtual string nif
		{
			get;
			set;
		}

        [Required]
        [StringLength(50, MinimumLength = 2)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        public virtual string nombre
		{
			get;
			set;
		}

        [Required]
        [DataType(DataType.PhoneNumber)]
        public virtual string telefono
		{
			get;
			set;
		}

        [Required]
        [DataType(DataType.EmailAddress)]
        public virtual string correoElectronico
		{
			get;
			set;
		}

        [StringLength(50, MinimumLength = 3)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        public virtual string direccion
		{
			get;
			set;
		}

        [StringLength(50, MinimumLength = 3)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        public virtual string localidad
		{
			get;
			set;
		}

        [StringLength(50, MinimumLength = 3)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        public virtual string provincia
		{
			get;
			set;
		}

        [DataType(DataType.PostalCode)]
        public virtual string codigoPostal
		{
			get;
			set;
		}

        [StringLength(50, MinimumLength = 3)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        public virtual string pais
		{
			get;
			set;
		}

        [Required]
        [StringLength(50, MinimumLength = 2)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        public virtual string apellidos
		{
			get;
			set;
		}

        [Key]
		public virtual int idPersona
		{
			get;
			set;
		}

        [ForeignKey("idProveedor")]
        public virtual Proveedor Proveedor
		{
			get;
			set;
		}

	}
}

