//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo se genero mediante una herramienta.
//     Los cambios del archivo se perderan si se regenera el codigo.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;

namespace TeamCatHotel.Models
{
        public class Plato
	{
        [Required]
        [StringLength(50, MinimumLength = 2)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        public virtual string nombre
		{
			get;
			set;
		}

        [Key]
		public virtual int idPlato
		{
			get;
			set;
		}

		public virtual ICollection<PlatoMenu> PlatoMenu
        {
			get;
			set;
		}

	}
}

