//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo se genero mediante una herramienta.
//     Los cambios del archivo se perderan si se regenera el codigo.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;

namespace TeamCatHotel.Models
{
	public class Producto
	{
        [Required]
        [Range(0, 1000)]
        public virtual int cantidad
		{
			get;
			set;
		}
        [Required]
        [Range(1, 1000)]
        public virtual int limiteMinimo
		{
			get;
			set;
		}
        [Required]
        [RegularExpression(@"^[A-Z]\d{8}$")]
        public virtual string localizador
		{
			get;
			set;
		}
        [Required]
        [StringLength(60, MinimumLength = 5)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        public virtual string categoria
		{
			get;
			set;
		}
        [StringLength(60, MinimumLength = 5)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        public virtual string descripcion
		{
			get;
			set;
		}
        [Required]
        [StringLength(60, MinimumLength = 2)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        public virtual string nombre
		{
			get;
			set;
		}
        [Required]
        [Range(1, 1000)]
        [DataType(DataType.Currency)]
        public virtual float precio
		{
			get;
			set;
		}
        [Key]
        public virtual int idProducto
		{
			get;
			set;
		}

		public virtual ICollection<LineaPedido> LineasPedido
		{
			get;
			set;
		}

		public virtual ICollection<ProductoProveedor> ProductoProveedor
		{
			get;
			set;
		}
	}
}

