//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo se genero mediante una herramienta.
//     Los cambios del archivo se perderan si se regenera el codigo.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;

namespace TeamCatHotel.Models
{
    public class ProductoProveedor
    {
        public virtual float precio
        {
            get;
            set;
        }

        [Key]
        public virtual int idProductoProveedor
        {
            get;
            set;
        }

        [ForeignKey("idProducto")]
        public virtual Producto Producto
        {
            get;
            set;
        }

        [ForeignKey("idProveedor")]
        public virtual Proveedor Proveedor
        {
            get;
            set;
        }

    }
}

