//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo se genero mediante una herramienta.
//     Los cambios del archivo se perderan si se regenera el codigo.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;

namespace TeamCatHotel.Models
{


	public class Proveedor
	{
        [Required]
        [StringLength(60, MinimumLength = 10)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        public virtual string numeroCuenta
		{
			get;
			set;
		}
        [Required]
        [StringLength(60, MinimumLength = 3)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        public virtual string nombre
		{
			get;
			set;
		}
        [Required]
        [StringLength(20, MinimumLength = 5)]
        [RegularExpression(@"^(\d{8}[A-Z])$")]
        public virtual string cif
		{
			get;
			set;
		}
        [Required]
        [StringLength(60, MinimumLength = 5)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        public virtual string direccion
		{
			get;
			set;
		}
        [DataType(DataType.EmailAddress)]
        public virtual string correoElectronico
		{
			get;
			set;
		}
        [Required]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        public virtual string localidad
		{
			get;
			set;
		}
        [Required]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        public virtual string provincia
		{
			get;
			set;
		}
        [Required]
        [StringLength(30, MinimumLength = 5)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        public virtual string pais
		{
			get;
			set;
		}
        [Key]
        public virtual int idProveedor
		{
			get;
			set;
		}

		public virtual ICollection<Pedido> Pedidos
		{
			get;
			set;
		}

        [ForeignKey("idPersona")]
        public virtual Persona Persona
		{
			get;
			set;
		}

		public virtual ICollection<ProductoProveedor> ProductoProveedor
		{
			get;
			set;
		}

	}
}

