//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo se genero mediante una herramienta.
//     Los cambios del archivo se perderan si se regenera el codigo.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;

namespace TeamCatHotel.Models
{
    
    public class Servicio
	{
        [StringLength(200, MinimumLength = 5)]
        [RegularExpression(@"^[A-Z0-9]+[a-zA-Z0-9''-'\s]*$")]
        public virtual string descripcion
		{
			get;
			set;
		}
        [StringLength(200, MinimumLength = 2)]
        [RegularExpression(@"^[A-Z0-9]+[a-zA-Z0-9''-'\s]*$")]
        public virtual string nombre
		{
			get;
			set;
		}
        [DataType(DataType.Currency)]
        public virtual float precio
		{
			get;
			set;
		}
        [Key]
        public virtual int idServicio
		{
			get;
			set;
		}
        [ForeignKey("idReserva")]
		public virtual ICollection<ReservaServicio> ReservasServicio
		{
			get;
			set;
		}
	}
}

